services:
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/backend/Dockerfile
    container_name: nestjs_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV}
      CORS_ORIGINS: ${CORS_ORIGINS}
    volumes:
      - ../backend/uploads:/app/uploads

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend/Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8080/api}
    container_name: react_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"